## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [10]:
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

In [12]:
lr = linear_model.LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
mean_squared_error(y_test, y_pred)

25.407976717074945

In [13]:
lr.coef_

array([-1.14743504e-01,  4.70875035e-02,  8.70282354e-03,  3.23818824e+00,
       -1.67240567e+01,  3.87662996e+00, -1.08218769e-02, -1.54144627e+00,
        2.92604151e-01, -1.33989537e-02, -9.07306805e-01,  8.91271054e-03,
       -4.58747039e-01])

In [14]:
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)

In [15]:
lasso.coef_

array([-0.10460997,  0.04881541, -0.04507749,  1.15331258, -0.        ,
        3.81707075, -0.02085665, -1.23526694,  0.25920388, -0.01516558,
       -0.74728244,  0.00973548, -0.4998582 ])

In [16]:
mean_squared_error(y_test, y_pred)

26.441443271372922

In [17]:
ridge = linear_model.Ridge(alpha=0.1)
ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)

In [18]:
ridge.coef_

array([-1.14125970e-01,  4.72144095e-02,  3.30466957e-03,  3.20052271e+00,
       -1.55057123e+01,  3.88649056e+00, -1.19216295e-02, -1.52356227e+00,
        2.89503886e-01, -1.34748440e-02, -8.94652812e-01,  8.97004994e-03,
       -4.60013401e-01])

In [19]:
mean_squared_error(y_test, y_pred)

25.44334799292967